# Generated by Django 5.1.1 on 2024-10-12 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_fname', models.CharField(max_length=20)),
                ('contact_lname', models.CharField(max_length=40)),
                ('shipping_address', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=40, unique=True)),
                ('customer_phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('forecast_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_company', models.CharField(max_length=20)),
                ('to_company', models.CharField(max_length=20)),
                ('customer_order_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_type', models.CharField(max_length=20)),
                ('key_metrics', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardReports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardVisuals',
            fields=[
                ('visual_id', models.AutoField(primary_key=True, serialize=False)),
                ('visual_type', models.CharField(max_length=50)),
                ('data_source', models.CharField(max_length=50)),
                ('date_range', models.CharField(max_length=50)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResults',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('forecast_quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastingPreferences',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_time_range', models.CharField(max_length=50)),
                ('desired_safety_stock', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_desc', models.CharField(max_length=255)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customerorder')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sold_quantity', models.IntegerField()),
                ('restock_quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderThreshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('reorder_point', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDateRange',
            fields=[
                ('date_range_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.IntegerField()),
                ('shipping_company', models.IntegerField()),
                ('shipped_date', models.DateField()),
                ('est_delivery_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('po_date', models.DateField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='UserDashSettings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_visuals', models.CharField(max_length=50)),
                ('default_report_type', models.CharField(max_length=50)),
                ('default_date_range', models.CharField(max_length=50)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customerorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'inventory', 'order')},
            },
        ),
    ]
