# Generated by Django 5.1.1 on 2024-10-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_audittrail_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.customerorder'),
        ),
    ]
