# Generated by Django 5.1.1 on 2024-10-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_audittrail_inventory_remove_audittrail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
