# Generated by Django 5.1.1 on 2024-10-17 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_location_postal_code_alter_location_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='restock_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='sold_quantity',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('return', 'Return'), ('adjustment', 'Adjustment')], default='restock', max_length=20),
            preserve_default=False,
        ),
    ]
