# Generated by Django 5.1.1 on 2024-10-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_audittrail_is_deleted_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='current_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
