# Generated by Django 5.1.1 on 2024-10-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_customerorder_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_company',
            field=models.CharField(max_length=40),
        ),
    ]
