# Generated by Django 5.1.1 on 2024-10-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_alter_shipment_shipping_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_company',
            field=models.CharField(default='To Be Determined', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
