# Generated by Django 5.1.2 on 2024-10-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_supplierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderthreshold',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.supplier'),
        ),
    ]
