# Generated by Django 5.1.1 on 2024-10-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.category'),
            preserve_default=False,
        ),
    ]
