# Generated by Django 5.1.2 on 2024-11-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_category'),
        ('db', '0016_supplierorder'),
    ]

    operations = [
    ]
