# Generated by Django 5.1.2 on 2024-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_reorderthreshold_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_inventory_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='problem_par',
            field=models.IntegerField(default=5),
        ),
    ]
