# Generated by Django 5.1.2 on 2024-11-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_merge_0016_category_0016_supplierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastingpreferences',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.category'),
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.customer'),
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.supplier'),
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='trend_direction',
            field=models.CharField(blank=True, choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='trend_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, to='db.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reorderthreshold',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.supplier'),
        ),
    ]
