# Generated by Django 5.1.1 on 2024-11-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_inventory_category'),
        ('db', '0017_reorderthreshold_supplier'),
    ]

    operations = [
    ]
