# Generated by Django 5.1.2 on 2024-11-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_inventory_low_inventory_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='problem_par',
        ),
    ]
