# Generated by Django 5.1.1 on 2024-11-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_merge_20241102_0219'),
        ('db', '0018_merge_20241102_1220'),
    ]

    operations = [
    ]
