# Generated by Django 5.1.1 on 2024-11-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_merge_20241030_2002'),
        ('db', '0019_merge_20241103_1627'),
    ]

    operations = [
    ]
