# Generated by Django 5.1.2 on 2024-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_merge_20241106_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_inventory_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
