# Generated by Django 5.1.1 on 2024-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_merge_20241106_2000'),
        ('db', '0021_inventory_low_inventory_threshold'),
    ]

    operations = [
    ]
