# Generated by Django 5.1.2 on 2024-11-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_inventory_low_inventory_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='low_inventory_threshold',
        ),
    ]
