# Generated by Django 5.1.1 on 2024-11-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_merge_20241104_1618'),
        ('db', '0022_merge_20241111_1133'),
    ]

    operations = [
    ]
