# Generated by Django 5.1.2 on 2024-11-11 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_remove_inventory_low_inventory_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.customerorder'),
        ),
    ]
