# Generated by Django 5.1.1 on 2024-11-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_merge_20241111_1304'),
        ('db', '0024_remove_inventory_low_inventory_threshold'),
    ]

    operations = [
    ]
