# Generated by Django 5.1.1 on 2024-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_forecastingpreferences_category_and_more'),
        ('db', '0025_merge_20241113_1220'),
    ]

    operations = [
    ]
