# Generated by Django 5.1.2 on 2024-11-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_remove_notifications_notification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
    ]
