# Generated by Django 5.1.1 on 2024-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_merge_20241114_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastingpreferences',
            old_name='vendor',
            new_name='supplier',
        ),
    ]
