# Generated by Django 5.1.1 on 2024-11-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_merge_20241114_1403'),
        ('db', '0027_rename_vendor_forecastingpreferences_supplier'),
    ]

    operations = [
    ]
