# Generated by Django 5.1.1 on 2024-11-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_merge_20241115_0334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('inventory_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_category_name', models.CharField(max_length=50, unique=True)),
                ('inventory_category_description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=5)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='forecastingpreferences',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact_fname',
            new_name='customer_business_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact_lname',
            new_name='customer_lname',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='cost',
            new_name='item_cost',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='forecast_level',
            new_name='item_forecast_level',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='item_quantity',
        ),
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='quantity',
            new_name='remaining_item_quantity',
        ),
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='remaining_quantity',
            new_name='transaction_quantity',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_quantity',
            new_name='purchase_order_quantity',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_email',
            new_name='supplier_email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_phone',
            new_name='supplier_phone',
        ),
        migrations.AddField(
            model_name='forecastingpreferences',
            name='inventory_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.CASCADE, to='db.inventorycategory'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='SalesOrderItem',
        ),
        migrations.RenameModel(
            old_name='Shipment',
            new_name='SalesOrderShipment',
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_company', models.CharField(max_length=20)),
                ('to_company', models.CharField(max_length=20)),
                ('customer_order_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.orderstatus')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shippingaddress')),
            ],
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesordershipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.salesorder'),
        ),
        migrations.AlterField(
            model_name='workson',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.salesorder'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shippingaddress'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=15)),
                ('Minit', models.CharField(blank=True, max_length=1, null=True)),
                ('Lname', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_phone_number', models.CharField(max_length=20, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
