# Generated by Django 5.1.1 on 2024-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_merge_20241115_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
