# Generated by Django 5.1.1 on 2024-12-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_profile_phone_number'),
        ('db', '0029_alter_audittrail_object_id'),
    ]

    operations = [
    ]
