# Generated by Django 5.1.1 on 2024-11-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_inventorycategory_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='is_deleted',
        ),
    ]
