# Generated by Django 5.1.1 on 2024-11-21 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_remove_inventory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.inventorycategory'),
        ),
    ]
